name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag api:$(date +%s)
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/poirecapi
