name: .NET Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.102
    - name: Restore dependencies
      run: dotnet restore
    - name: Lint
      run: dotnet format --include-generated --verbosity detailed --exclude WebApi/Migrations/ --verify-no-changes
    - name: Build
      run: dotnet build --no-restore
    - name: Upload to codecov
      uses: codecov/codecov-action@v2
      with: 
        token: 4cfaf34a-b13e-4116-936a-fc34ea9b2fa5
        file: TestResults/test.json
        flags: unittests
        verbose: true
